### ISSUE TITLE
export/link to png?

### ISSUE THREAD

**Issue by camypaj** [filhocf/infographics#10]
Hi all, this is more of a feature request than a "issue". I can't seem to find the updated version of the png file online, and no instructions on how to load/convert it somewhere in docs.. I've checked out the repo, and I assume different language are like "layers", but it's still non-trivial, and I guess it should be, right?
Edit: I see that it's a duplicate of  #7 in a way, but still.. It would be nice to make a small "howto", or just link the resulting image somewhere? Or am I wrong?

**Comment by camypaj** [comment]
on the second attempt, it does open on my pc, but if overloads all my cores, so as I said - it would make it more accessible to export/link a pdf/png/or even a printable jpg somewhere. :)

**Comment by ryantig** [comment]
Good tools for converting... [ImageMagick](https://www.imagemagick.org), [GIMP](https://www.gimp.org/), [Leptonica](http://www.leptonica.com/), [XnConvert](https://www.xnview.com/en/xnconvert/)

Aside: You might want to go svg to webp, which is smaller/tighter than png and it's a completely open format. Google makes cwebp available for Windows/Mac/Linux (source code, and pre-compiled binary) which does JPEG, PNG or TIFF format into WebP....
[Compiled cwebp](https://developers.google.com/speed/webp/docs/precompiled)

**Comment by filhocf** [comment]
@camypaj, please, open this issue in this repo.
https://github.com/filhocf/debian-infographic
