### ISSUE TITLE
"not a valid URI" error for infographic_debian.svg on GitHub

### ISSUE THREAD

**Issue by yellowsoar** [filhocf/infographics#13]
# Reproduce

https://raw.githubusercontent.com/filhocf/infographics/beaa3ca8c8ee7235913daa6e0c7853f1dac63e65/debian/infographic_debian.svg

# Error message

```
This page contains the following errors:

error on line 5 at column 99: xmlns:ns0: '&#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;ns_ai;' is not a valid URI
```

**Comment by raspitakesovertheworld** [comment]
I'm seeing the same error, only part of the infographic is loading, I also loaded in Inkscape and it does not display completed (without error)
With which app did you edit it? Could you possibly save it in a format that is universal, but high resolution, like PDF? The bitmap versions are low resolution and a lot of detail gets lost when zooming in. This is a really amazing overview about Linux, opensource and Debian. Is there a way to fix it?

**Comment by filhocf** [comment]
A bug without solution. I tried to open with Inkscape 1.3.x and works fine again.
