### ISSUE TITLE
SVG file open incorrectly

### ISSUE THREAD

**Issue by mudongliang** [filhocf/infographics#2]
When I use Image Viewer to open svg file , there are some black holes in picture !
Why ? How to solve it ???

**Comment by mudongliang** [comment]
It opened like this !
![screenshot from 2015-02-06 13 45 03](https://cloud.githubusercontent.com/assets/6214861/6075079/6ed15048-ae06-11e4-924f-91dfefb5d3ca.png)

**Comment by mikefaille** [comment]
@mudongliang  I suggest you to send a bug report at : https://bugzilla.gnome.org/browse.cgi?product=eog

**Comment by mudongliang** [comment]
I can see the picture online in the webpage !So the problem it is not source of picture !So I think it is a bug too!

**Comment by mikefaille** [comment]
@mudongliang You can see the picture on a web page cause I'd convert this picture to jpg format.

**Comment by mudongliang** [comment]
Thank you !

2015-02-06 14:42 GMT+08:00 mikefaille notifications@github.com:
