### ISSUE TITLE
How do you draw the infographic_debian.svg?

### ISSUE THREAD

**Issue by mudongliang** [filhocf/infographics#3]
https://github.com/filhocf/infographics/blob/master/debian/infographic_debian.svg
About this picture , the probem in #2 still exists ,although you update 2.1 version.
![screenshot from 2015-04-24 19 54 30](https://cloud.githubusercontent.com/assets/6214861/7318197/c7e5ca8c-eabb-11e4-955e-32427292111e.png)

Which tool do you use to draw this picture? If I can understand the creation of this picture , I can help you to maintain this folder!
Thank you !

**Comment by Skywalker13** [comment]
It's done with Inkscape
