### ISSUE TITLE
bronk images

### ISSUE THREAD

**Issue by valessiobrito** [filhocf/infographics#5]
Sorry report in pt_BR.
1. Algumas imagens estão com links quebrados;   No inkscape tem uma extensão em Imagens, chamada "Embutir imagens",  ela vai incorporar todas imagens ao trabalho;
2. Depois em "Arquivo" tem uma funcionalidade "Limpar documento", que faz limpeza de cabeçalhos ou referências quais não estão sendo utilizado.  Reduzindo possivelmente o SVG.

Log error:

*\* (inkscape:20501): WARNING **: <image xlink:href="/home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-text-ja.png"> did not resolve to a valid image file (base dir is /home/valessio/Desenvolvimento/infographics/debian), now trying sodipodi:absref="/home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-text-ja.png"

*\* (inkscape:20501): WARNING **: Unable to open linked file: /home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-text-ja.png

*\* (inkscape:20501): WARNING **: <image xlink:href="/home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-text-gr.png"> did not resolve to a valid image file (base dir is /home/valessio/Desenvolvimento/infographics/debian), now trying sodipodi:absref="/home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-text-gr.png"

*\* (inkscape:20501): WARNING **: Unable to open linked file: /home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-text-gr.png

*\* (inkscape:20501): WARNING **: <image xlink:href="/home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-swirl.png"> did not resolve to a valid image file (base dir is /home/valessio/Desenvolvimento/infographics/debian), now trying sodipodi:absref="/home/filhocf/projetos/debian/artes/imagens/skolelinux-logo-swirl.png"

**Comment by filhocf** [comment]
SVG limpo. Obrigado.
