### ISSUE TITLE
Missing Debian Pure Blends?

### ISSUE THREAD

**Issue by l** [filhocf/infographics#6]
Dear Claudio (@filhocf),

Currently, Skol linux, Debian Med, Debian GIS,
Debian Science, and DebiChem are printed as Pure Blends.
However, there are lots of [other blends](https://www.debian.org/blends/) (Ex. Debian Astro).

We think that it would be nice if you add other blends also.

Sincerely yours,
Ryuunosuke Ayanokouzi

**Comment by olebole** [comment]
May I specifically ask for inclusion of [Debian-Astro](https://blends.debian.org/astro)?
For Debian Astro, you may find the logo in our [git repository](https://anonscm.debian.org/cgit/debian-astro/debian-astro-logo.git/). SVG is [here](https://anonscm.debian.org/cgit/debian-astro/debian-astro-logo.git/plain/Debian-Astro-logo.svg).

**Comment by filhocf** [comment]
Hi @olebole 

Thank you by your suggestion. I will add it when possible. I have one ask: when appeared Debian-Astro? Do you know in what year (and month, if possible)?

**Comment by olebole** [comment]
It depends of what you mean with "appeared": The [official announcement](https://lists.debian.org/debian-astro/2016/03/msg00006.html) is in March 2016, however the mailing list was [created](https://lists.debian.org/debian-astro/2014/03/msg00001.html) already in March 2014. I would suggest to take the official announcement here.

**Comment by filhocf** [comment]
Thank you, @olebole. I already adding the Debian-Astro with DebConf 17. Tomorrow, we have it finished.

**Comment by filhocf** [comment]
Comitted.
