### ISSUE TITLE
How to open?

### ISSUE THREAD

**Issue by seirotis** [filhocf/infographics#7]
i can't open 'infographic_debian.svg' in my browser. it doesn't show everything. how can i generate a jpg from it? pls help or provide preproduced png or jpg. thx.

**Comment by Skywalker13** [comment]
Inkscape

**Comment by filhocf** [comment]
Thank you, @Skywalker13 .

@seirotis , you need Inkscape because this SVG is a compacted SVG, the default format of Inkscape. Isn't a plain SVG, where the browser can see it.

**Comment by seirotis** [comment]
@filhocf I was able to open the svg now, but everything is in spanish. How can I switch to the english version?

**Comment by seirotis** [comment]
@filhocf Ping :)

**Comment by alvarezp** [comment]
Try playing with the layers.
