### ISSUE TITLE
Gerar uma versão Interativa

### ISSUE THREAD

**Issue by valessiobrito** [filhocf/infographics#8]
Para pilhar na evoluçào do Infográfico, fica a sugestão de criar uma versão interativa com Sozi
http://sozi.baierouge.fr/

Sozi vai colocar um cabeçalho em JavaScript e pode trabalhar a interatividade da sequência dos slides em outra camada.

**Comment by filhocf** [comment]
@valessiobrito, please, open this issue in this repo.
https://github.com/filhocf/debian-infographic
