### ISSUE TITLE
Update with stretch

### ISSUE THREAD

**Issue by dcpc007** [filhocf/infographics#9]
Hi, have you a new version with Stretch as stable please ?

(Super work for previous ! thx)

**Comment by koedoyoshida** [comment]
I want New version with Stretch as stable too.
I tryed update it, but with my skills I could not fix it.
Even if it is not corrected,
It is planned to be used at the OSS event in Japan next February.
(Thank you very much!)

**Comment by filhocf** [comment]
Sorry @koedoyoshida , but I haven't time to work in update the infographic. 
Anyway, when you will use it?

**Comment by koedoyoshida** [comment]
@filhocf Thank you.
The event will be held this weekend.
https://www.ospn.jp/osc2018-spring/
I will use it in the current version.
The next event is scheduled for September.

**Comment by sblondon** [comment]
@koedoyoshida It's not interesting for your need but I made a fork with an update for apache and libreoffice logos (see https://github.com/sblondon/infographics).
I will not delete it until it's merged.

If you plan to print the picture for the conference in september, you will get a very lightly better poster.

**Comment by raspitakesovertheworld** [comment]
Wow, this must be the best poster that explains what Debian is and how it works, really amazing! I plan to print a poster of it, thank you for the amazing work!

**Comment by filhocf** [comment]
@dcpc007, please, open this issue in this repo.
https://github.com/filhocf/debian-infographic
